---
title: "Modelo Matematico CBR"
author: P.N. de Lima, D. B. Goldmeyer, L. F. R. Camargo, A. Dresch, D. P. Lacerda,
  T. Kunrath
date: "junho de 2017"
output:
  word_document: default
  pdf_document:
    keep_tex: yes
    latex_engine: xelatex
    number_sections: yes
    toc: yes
    toc_depth: 6
  html_document: default
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Modelo Matemático - Razão Benefício-Custo
Este documento contém uma definição do modelo matemático que suporta a calculadora de custos e benefícios de inciativas em SST.

## CBR - Razão Benefício-Custo
A razão benefício-custo $\alpha$ corresponde à razão do somatório dos custos $C_i$ onde $i$ representa o índice de custos e $B_j$ os benefícios a valor presente.

$$\alpha = \frac{\sum_{i=1}^{I} B_{i}} {\sum_{j=1}^{J} C_{j}}$$

### Fluxo de Caixa em Valor Presente
Os fluxos de caixa devem ser ajustados a valor presente utilizando-se uma taxa de atratividade $\theta$ definida pelo usuário do modelo. Tal taxa será utilizada para trazer os valores de fluxo de caixa a valor presente.

$$B_i(t) = \frac{b_i}{(1+\theta)^t}$$
### Calculo da Falta
Em todos os casos, o número de faltas será calculado a partir da multiplicação do número de funcionários da empresa $f$ e a taxa de falta $T_falta$, conforme equação abaixo: 

$$Nfalta = f * T_falta$$ 
### Calculo dos Eventos
Em todos os casos, o número de eventos será calculado a partir da multiplicação do número de funcionários da empresa $f$, probabilidade do evento "k" ocorrer $Pev_{k}$, e a probabilidade da consequência $"c"$ ocorrer $Pev_c$. Onde $k$ pertence ao conjunto K= [típico, trajeto, doença não ocupacional]. E $c$ pertece ao conjunto C =[ afastamento<15, afastamento>15, óbito, sem afastamento].  

$$Nev_{c,k}= f * Pev_{k} * Pev_{c} \ \forall \ c \  \in \ C,  \ k \  \in \ K$$
#### B92
$$N_{b92} = Nev_{af_{<15},k} * P_{inval} , onde \ k = (típico \ , trajeto \  ou \ doença \ ocupacional) $$
#### B91

$$N_{b91} = Nev_{af>15}, ocupacional} * P_{inval}$$
#### B94

$$N_{b94} = (Nev_{af>15},_{traj} + Nev_{af>15},_{tipico}  ) * P_{inval}$$
#### B93

$$N_{b93} = Nev_{obito, k}$$
#### Numero de benefícios acumulados 

$$N_B = \sum_{i=1}^{B} n_iacumulado \ \forall \ i \  \in \ B$$

### Calculo dos Benefícios
Em todos os casos, o benefício será calculado a partir da diferença em valores monetários de uma variável financeira sem a iniciativa em SST e com a iniciativa em SST. Exemplificando, o benefício gerado pela redução de absenteísmo $B_{abs}$ será calculado a partir da seguinte equação.

$$B_i = {D}_{i, ci} - {D}_{i, si}$$
Exemplificando, se uma empresa, sem uma iniciativa em SST terá $20000$ reais em desepesas com absenteísmo, e com esta iniciativa terá $15000$, o benefício oriúndo desta inciativa, apenas relacionado a absenteísmo será:

$$B_{abs} = {D}_{abs, ci} - {D}_{abs, si} = (-15000)-(-20000) = 5000$$


#### Despesas Evitáveis

##### Despesas com Reclamatórias Trabalhistas
Esta subcategoria compreende as despesas evitadas com reclamatórias trabalhistas (objeto da ação relacionadas à doenças e acidentes do trabalho) após a implementação integral da iniciativa.

Parâmetros:
$c_{med}$: Custo Médio da Reclamatória
$n_{reclamatorias}$: Número de Reclamatórias trabalhistas relacionadas a SST.

$${D}_{reclamatorias} = c_{med}*n_{reclamatorias} $$

###### Número de Reclamatórias Trabalhistas

$$n_{reclamatorias} = f_{desligados} * p_{ajuizarEganharreclamatoria} $$

Parâmetros:
$p_{ajuizarEganharreclamatoria}$: Probabilidade de um funcionário demitido entrar com uma reclamatória e ganhar a causa.
$f_{desligados}$: Número de Funcionários desligados pela empresa.

Possibilidade 1: Considerar uma única probabilidade de ajuizar e ganhar uma ação reclamatória. Esta probabilidade vezes o número de funcionários gera o número de reclamatórias trabalhistas a pagar.

Possibilidade 2: Separar o ajuizamento da ação do ganho da ação. Desta maneira é possível calcular o custo em ações mesmo quando o funcionário não ganhou a ação. A princípio estamos na possibilidade 1.

##### Acidente / Doença Ocupacional - Invalidez

Esta subcategoria compreende as despesas evitadas com incapacitação parcial ou total provocada por acidente típico, doença ocupacional ou acidente de trajeto após a implementação integral da iniciativa.

Possibilidade 1: Todos os custos incorridos nesta rúbrica entram para o calculo do FAP e não deveriam ser contados em duplicidade.
Possibilidade 2: Existem despesas que não estão em nenhuma outra categoria e que deveriam ser contabilizados aqui. A princípio estamos na possibilidade 1. A categoria será excluída caso a possibilidade 1 se confirme.

##### Ações Regressivas (NTEP)
Esta subcategoria compreende as despesas evitadas com ações regressivas do INSS após a implementação integral da iniciativa.

A Ação Regressiva representa o o ressarcimento de pagamento de benefícios acidentários do empregador ao INSS. Lei 8213/91, artigo 120 :A ação regressiva é a penalização adicional relacionada ao B91 - B94.

###### Ações Regressivas Relacionadas ao INSS

$$D_{ações regressivas INSS} =  \sum_{i=1}^{B} n_iacumulado * p_iacaoregressiva * (f_{crise}*crise) * tregressiva_{i}  $$

Dúvida: O NTEP já estará contabilizado integralmente pelo FAP? Sim: Então precisa estar aqui. Não: Então
Dúvida 2: Crise econômica deve modular esta probabilidade? Que variáveis de contexto devem modular que variáveis de input?


###### Ações Regressivas Relacionadas ao Plano de Saúde

$$D_{ações regressivas SUS} =  TotaldeAfastamentosAcumulado * PrecentualTratamentoNoSUS * (f_{crise}*crise) * PercentualCobrancaSUS/PlanodeSaude * ticketmedio$$

##### Ausência para Tratamento

Esta subcategoria compreende as despesas evitadas com a ausência do trabalhador afastado para tratamento após a implementação integral da iniciativa.

Esta categoria irá para a categoria de absenteísmo.

##### Despesas Médicas

Esta subcategoria compreende as despesas evitadas com medicamento e atendimento médico para tratamento dos acidentes de trabalho após a implementação integral da iniciativa.

$$D_{medicas} = (\sum_{k=1}^{K} n_{acidentesk}) * d_{medio}$$

##### Redução de Valores do plano de Saúde 
Esta subcategoria compreende as despesas evitadas com planos de saúde via alteração da taxa de sinistralidade após a implementação integral da iniciativa.
$$D_{planosaude} = D_{planosaudebase} * desc_{plano}$$

Dúvida: Como calcular o desconto no plano de saúde a partir das demais variáveis?
$$desc_{plano}(TaxaSinistralidade) =  ?? $$

##### Reabilitação:
Usará (f_{crise}*crise)


##### Interrupção Operacional por Acidente/Morte

$$D_{interdicao} = n_{acidentestipico} * dias * lucrocessante$$

##### Interdições Por Fiscalização
$$D_{interdicao} = p_{interdicao} * (f_{crise}*crise) * dias * lucrocessante $$


##### Reabilitação do trabalhador

Os custos para reabilitação do trabalhador deve compreender custos relacionados a RH, SST, recapacitação, adequação do posto de trabalho, e adequação do salário.


#### Benefício Não Capturado

##### Exposição à Multas

$$D_{multas}= (f_{crise}*crise) * N_l * C_{med_l}$$
###### Número de multas (N_l)

$$N_l = Atendlegisl_l * p_{multa_l}$$
###### Probabilidade multa (p_{multa_l})

$$ p_{multa_l} = if Nref => Nev then p_{multapriori_l}$$




##### Reduções Fiscais

FAP, RAT e SAT: As despesas com seguro acidentário do trabalho $D_{sat}$ serão calculadas de acordo com as estimativas do $FAP$ ($0,005 - 0,02$) e $RAT$ .

$$D_{sat} = RAT_{ajust}* F$$

###### Rat Ajustado

$$RAT_{ajust} = (FAP * RAT)$$
O $RAT$ varia entre 1 e 3, de acordo com o cnae da empresa em questão.
$$RAT \in {1,2,3}$$

###### FAP
O FAP, por sua vez, é calculado de acordo com os percentis de gravidade $p_g$, frequência $p_{f}$ e custo$p_c$:

$$FAP = (0,5*p_g + 0,35*p_{f}+0,15*p_c)0,02$$

Percentis são calculados de acordo com os índices nos dois anos anteriores.* Os percentis dependem do posicionamento da empresa em relação às demais. Específicamente a função $Pos(I_{t-1},I_{t-2})$ é calculada pela previdência de acordo com os índices de todas as empresas no mesmo subgrupo do CNAE da empresa em questão. Ainda não foi definida uma maneira de estimar esta função.

$$p_t = \frac{100*(Pos(I_{t-1},I_{t-2})-1)}{n-1}$$

Será definida uma forma para estimar $p_t$.

###### Índice de Frequência

$$I_f = \frac{(n_{cats}+n_{b92}+n_{b91}+n_{b93})}{f} * 1000$$

###### Índice de gravidade
$$I_g = \frac{(0.1*n_{b91}+0.3*n_{b92}+0.5*n_{b93}+0.1*n_{b94})}{f}* 1000$$

###### Índice de Custo

$$I_c = \frac{c_{beneficios inss}}{folha media}/ * 1000$$

Custos de Benefícios: Considerar tempo médio de afastamento por tipo de afastamento (b91, b92, b93, b94) e o "ticket médio" de cada um destes benefícios.

##### B91, B92, B93, B,94, etc



$$b_i = n_i * p_i \ \forall b_i \in B$$

Obs: Será necessário possuir

#### Intangível

##### Imagem da Empresa

##### Engajamento / Clima Organizacional



#### Melhor Uso dos Recursos

##### Turnover

As despesas com Turnover $D_{tur}$ serão calculadas com base no número de funcionários afastados por problemas relacionados à SST $n_{afast}$ e no custo médio de substituição dos funcionários$c_{sub}$.

$$D_{tur} = (Nev_{af_{<15},k} + Nev_{obito,k}) * c_{sub}$$ 

Número de Afastamentos é calculado de acordo com a probabilidade de morte $p_{morte}$ e a probabilidade de afastamento por período menor que 15 dias $p_{>15}$

$$n_{afast} = p_{morte}*f + p_{>15}*f$$



###### Número de Afastamentos
O número de afastamentos $n_{afast}$ será estimado de acordo com a probabilidade de afastamento $\rho_{afast}$ e número de funcionários $f$:
$$n_{afast} = \rho_{afast} * f $$


##### Absenteísmo

As despesas com Absenteísmo $D_{abs}$ serão calculadas com base no número de dias de absenteísmo por problemas relacionados à SST $d_{abs}$, no número de horas trabalhadas por dia $h$ e no custo em mão de obra médio horário $c_{mdo}$.

$$D_{abs} = d_{abs} * h * c_{mdo}$$

###### Dias de Absenteísmo

$$ d_{abs} = (Nev_{af_{<15},k}} + Nfalta)*D_{medioafast_{<15}}$$

##### Variável Intermediária Acidentes
Número de Acidentes $Nac_{k}$ dp tipo $k$ é igual ao número de funcionários na empresas vezes o percentual de funcionários que se acidentou $Pac_{k}$. O tipo de acidente pode ser Típico, de Trajeto, Doença Ocupacional ou "Não Acidente".

$$Nac_{k} = f * Pac_{k} \ \forall k \in K$$

##### Afastamentos

Afastamentos < 15 dias:
$$naf_{<15k} = p_{<15} * Nac_{k}  \ \forall k \in K$$

Afastamentos > 15 dias:
$$naf_{>15k} = p_{>15} * Nac_{k}  \ \forall k \in K$$
Óbitos:
$$nob_{k} = p_{obitos} * Nac_{k}  \ \forall k \in K $$

Acidentes Sem Afastamento:
$$nsaf_{k} = p_{nsaf} *Nac_{k}  \ \forall k \in K $$


###### Número de Benefícios Concedidos
O número de Benefícios concedidos do tipo $i$ serão calculados...
b92  = ...
b93 = ...



###### Dias de Absenteísmo (Antigo)
Os dias de absenteísmo $d_{abs}$ serão estimados de acordo com a probabilidade de absenteísmo $\rho_{abs}$, número de funcionários $f$ e número de dias úteis do ano $d$:

$$d_{abs} = \rho_{abs} * f * d$$

##### Presenteísmo
##### Produtividade
##### Qualidade
Usar o número de acidentes típicos e doenças ocupacionais como proxies para o custo em qualidade, refugo e retrabalho?
##### Refugo e Retrabalho
Usar o número de acidentes típicos e doenças ocupacionais como proxies para o custo em qualidade, refugo e retrabalho?

É necessário também considerar acidentes de trajeto?

##### MP, Insumos, Equipamentos Operação


### Variáveis Intermediárias


### Custos

#### Custos de Implementação
